export const NOC_LIST = [
  // Europe
  { noc: "SRB", name: "Srbija",              alpha2: "RS" },
  { noc: "CRO", name: "Hrvatska",            alpha2: "HR" },
  { noc: "SLO", name: "Slovenija",           alpha2: "SI" },
  { noc: "BIH", name: "Bosna i Hercegovina", alpha2: "BA" },
  { noc: "MNE", name: "Crna Gora",           alpha2: "ME" },
  { noc: "MKD", name: "Severna Makedonija",  alpha2: "MK" },
  { noc: "ALB", name: "Albanija",            alpha2: "AL" },
  { noc: "AND", name: "Andora",              alpha2: "AD" },
  { noc: "ARM", name: "Jermenija",           alpha2: "AM" },
  { noc: "AUT", name: "Austrija",            alpha2: "AT" },
  { noc: "AZE", name: "Azerbejdžan",         alpha2: "AZ" },
  { noc: "BEL", name: "Belgija",             alpha2: "BE" },
  { noc: "BLR", name: "Belorusija",          alpha2: "BY" },
  { noc: "BUL", name: "Bugarska",            alpha2: "BG" },
  { noc: "CYP", name: "Kipar",               alpha2: "CY" },
  { noc: "CZE", name: "Češka",               alpha2: "CZ" },
  { noc: "DEN", name: "Danska",              alpha2: "DK" },
  { noc: "ESP", name: "Španija",             alpha2: "ES" },
  { noc: "EST", name: "Estonija",            alpha2: "EE" },
  { noc: "FIN", name: "Finska",              alpha2: "FI" },
  { noc: "FRA", name: "Francuska",           alpha2: "FR" },
  { noc: "GBR", name: "Velika Britanija",    alpha2: "GB" },
  { noc: "GEO", name: "Gruzija",             alpha2: "GE" },
  { noc: "GER", name: "Nemačka",             alpha2: "DE" },
  { noc: "GRE", name: "Grčka",               alpha2: "GR" },
  { noc: "HUN", name: "Mađarska",            alpha2: "HU" },
  { noc: "IRL", name: "Irska",               alpha2: "IE" },
  { noc: "ISL", name: "Island",              alpha2: "IS" },
  { noc: "ISR", name: "Izrael",              alpha2: "IL" },
  { noc: "ITA", name: "Italija",             alpha2: "IT" },
  { noc: "KOS", name: "Kosovo",              alpha2: "XK" },
  { noc: "LAT", name: "Letonija",            alpha2: "LV" },
  { noc: "LIE", name: "Lihtenštajn",         alpha2: "LI" },
  { noc: "LTU", name: "Litvanija",           alpha2: "LT" },
  { noc: "LUX", name: "Luksemburg",          alpha2: "LU" },
  { noc: "MDA", name: "Moldavija",           alpha2: "MD" },
  { noc: "MLT", name: "Malta",               alpha2: "MT" },
  { noc: "MON", name: "Monako",              alpha2: "MC" },
  { noc: "NED", name: "Holandija",           alpha2: "NL" },
  { noc: "NOR", name: "Norveška",            alpha2: "NO" },
  { noc: "POL", name: "Poljska",             alpha2: "PL" },
  { noc: "POR", name: "Portugalija",         alpha2: "PT" },
  { noc: "ROU", name: "Rumunija",            alpha2: "RO" },
  { noc: "RUS", name: "Rusija",              alpha2: "RU" },
  { noc: "SMR", name: "San Marino",          alpha2: "SM" },
  { noc: "SUI", name: "Švajcarska",          alpha2: "CH" },
  { noc: "SVK", name: "Slovačka",            alpha2: "SK" },
  { noc: "SWE", name: "Švedska",             alpha2: "SE" },
  { noc: "TUR", name: "Turska",              alpha2: "TR" },
  { noc: "UKR", name: "Ukrajina",            alpha2: "UA" },
  // Asia
  { noc: "AFG", name: "Avganistan",          alpha2: "AF" },
  { noc: "BAN", name: "Bangladeš",           alpha2: "BD" },
  { noc: "BHU", name: "Butan",               alpha2: "BT" },
  { noc: "BRN", name: "Brunej",              alpha2: "BN" },
  { noc: "CAM", name: "Kambodža",            alpha2: "KH" },
  { noc: "CHN", name: "Kina",                alpha2: "CN" },
  { noc: "HKG", name: "Hong Kong",           alpha2: "HK" },
  { noc: "INA", name: "Indonezija",          alpha2: "ID" },
  { noc: "IND", name: "Indija",              alpha2: "IN" },
  { noc: "IRI", name: "Iran",                alpha2: "IR" },
  { noc: "IRQ", name: "Irak",                alpha2: "IQ" },
  { noc: "JOR", name: "Jordan",              alpha2: "JO" },
  { noc: "JPN", name: "Japan",               alpha2: "JP" },
  { noc: "KAZ", name: "Kazahstan",           alpha2: "KZ" },
  { noc: "KGZ", name: "Kirgizstan",          alpha2: "KG" },
  { noc: "KOR", name: "Južna Koreja",        alpha2: "KR" },
  { noc: "KSA", name: "Saudijska Arabija",   alpha2: "SA" },
  { noc: "KUW", name: "Kuvajt",              alpha2: "KW" },
  { noc: "LAO", name: "Laos",                alpha2: "LA" },
  { noc: "LBN", name: "Liban",               alpha2: "LB" },
  { noc: "MAS", name: "Malezija",            alpha2: "MY" },
  { noc: "MDV", name: "Maldivi",             alpha2: "MV" },
  { noc: "MGL", name: "Mongolija",           alpha2: "MN" },
  { noc: "MYA", name: "Mjanmar",             alpha2: "MM" },
  { noc: "NEP", name: "Nepal",               alpha2: "NP" },
  { noc: "OMA", name: "Oman",                alpha2: "OM" },
  { noc: "PAK", name: "Pakistan",            alpha2: "PK" },
  { noc: "PHI", name: "Filipini",            alpha2: "PH" },
  { noc: "PRK", name: "Severna Koreja",      alpha2: "KP" },
  { noc: "QAT", name: "Katar",               alpha2: "QA" },
  { noc: "SGP", name: "Singapur",            alpha2: "SG" },
  { noc: "SRI", name: "Šri Lanka",           alpha2: "LK" },
  { noc: "SYR", name: "Sirija",              alpha2: "SY" },
  { noc: "TJK", name: "Tadžikistan",         alpha2: "TJ" },
  { noc: "TKM", name: "Turkmenistan",        alpha2: "TM" },
  { noc: "TLS", name: "Istočni Timor",       alpha2: "TL" },
  { noc: "TPE", name: "Kineski Tajpej",      alpha2: "TW" },
  { noc: "UAE", name: "UAE",                 alpha2: "AE" },
  { noc: "UZB", name: "Uzbekistan",          alpha2: "UZ" },
  { noc: "VIE", name: "Vijetnam",            alpha2: "VN" },
  { noc: "YEM", name: "Jemen",               alpha2: "YE" },
  // Africa
  { noc: "AGO", name: "Angola",              alpha2: "AO" },
  { noc: "ALG", name: "Alžir",               alpha2: "DZ" },
  { noc: "BEN", name: "Benin",               alpha2: "BJ" },
  { noc: "BOT", name: "Bocvana",             alpha2: "BW" },
  { noc: "BUR", name: "Burkina Faso",        alpha2: "BF" },
  { noc: "CAF", name: "Centralnoafrička Rep.", alpha2: "CF" },
  { noc: "CGO", name: "Kongo",               alpha2: "CG" },
  { noc: "CHA", name: "Čad",                 alpha2: "TD" },
  { noc: "CIV", name: "Obala Slonovače",     alpha2: "CI" },
  { noc: "CMR", name: "Kamerun",             alpha2: "CM" },
  { noc: "COD", name: "DR Kongo",            alpha2: "CD" },
  { noc: "COM", name: "Komori",              alpha2: "KM" },
  { noc: "CPV", name: "Zelenortska Ostrva",  alpha2: "CV" },
  { noc: "DJI", name: "Džibuti",             alpha2: "DJ" },
  { noc: "EGY", name: "Egipat",              alpha2: "EG" },
  { noc: "ERI", name: "Eritreja",            alpha2: "ER" },
  { noc: "ESW", name: "Esvatini",            alpha2: "SZ" },
  { noc: "ETH", name: "Etiopija",            alpha2: "ET" },
  { noc: "GAB", name: "Gabon",               alpha2: "GA" },
  { noc: "GAM", name: "Gambija",             alpha2: "GM" },
  { noc: "GBS", name: "Gvineja Bisao",       alpha2: "GW" },
  { noc: "GHA", name: "Gana",                alpha2: "GH" },
  { noc: "GUI", name: "Gvineja",             alpha2: "GN" },
  { noc: "GUQ", name: "Ekvatorialna Gvineja", alpha2: "GQ" },
  { noc: "KEN", name: "Kenija",              alpha2: "KE" },
  { noc: "LBA", name: "Libija",              alpha2: "LY" },
  { noc: "LES", name: "Lesoto",              alpha2: "LS" },
  { noc: "LIB", name: "Liberija",            alpha2: "LR" },
  { noc: "MAD", name: "Madagaskar",          alpha2: "MG" },
  { noc: "MAR", name: "Maroko",              alpha2: "MA" },
  { noc: "MAW", name: "Malavi",              alpha2: "MW" },
  { noc: "MLI", name: "Mali",                alpha2: "ML" },
  { noc: "MOZ", name: "Mozambik",            alpha2: "MZ" },
  { noc: "MRI", name: "Mauricijus",          alpha2: "MU" },
  { noc: "MTN", name: "Mauritanija",         alpha2: "MR" },
  { noc: "NAM", name: "Namibija",            alpha2: "NA" },
  { noc: "NGR", name: "Nigerija",            alpha2: "NG" },
  { noc: "NIG", name: "Niger",               alpha2: "NE" },
  { noc: "RSA", name: "Južnoafrička Rep.",   alpha2: "ZA" },
  { noc: "RWA", name: "Ruanda",              alpha2: "RW" },
  { noc: "SEN", name: "Senegal",             alpha2: "SN" },
  { noc: "SEY", name: "Sejšeli",             alpha2: "SC" },
  { noc: "SLE", name: "Sijera Leone",        alpha2: "SL" },
  { noc: "SOM", name: "Somalija",            alpha2: "SO" },
  { noc: "SSD", name: "Južni Sudan",         alpha2: "SS" },
  { noc: "STP", name: "Sveti Toma i Princip", alpha2: "ST" },
  { noc: "SUD", name: "Sudan",               alpha2: "SD" },
  { noc: "TAN", name: "Tanzanija",           alpha2: "TZ" },
  { noc: "TOG", name: "Togo",                alpha2: "TG" },
  { noc: "TUN", name: "Tunis",               alpha2: "TN" },
  { noc: "UGA", name: "Uganda",              alpha2: "UG" },
  { noc: "ZAM", name: "Zambija",             alpha2: "ZM" },
  { noc: "ZIM", name: "Zimbabve",            alpha2: "ZW" },
  // Americas
  { noc: "ANT", name: "Antigva i Barbuda",   alpha2: "AG" },
  { noc: "ARG", name: "Argentina",           alpha2: "AR" },
  { noc: "ARU", name: "Aruba",               alpha2: "AW" },
  { noc: "BAH", name: "Bahami",              alpha2: "BS" },
  { noc: "BAR", name: "Barbados",            alpha2: "BB" },
  { noc: "BER", name: "Bermuda",             alpha2: "BM" },
  { noc: "BOL", name: "Bolivija",            alpha2: "BO" },
  { noc: "BRA", name: "Brazil",              alpha2: "BR" },
  { noc: "CAN", name: "Kanada",              alpha2: "CA" },
  { noc: "CAY", name: "Kajmanska Ostrva",    alpha2: "KY" },
  { noc: "CHI", name: "Čile",                alpha2: "CL" },
  { noc: "COL", name: "Kolumbija",           alpha2: "CO" },
  { noc: "CRC", name: "Kostarika",           alpha2: "CR" },
  { noc: "CUB", name: "Kuba",                alpha2: "CU" },
  { noc: "DMA", name: "Dominika",            alpha2: "DM" },
  { noc: "DOM", name: "Dominikanska Rep.",   alpha2: "DO" },
  { noc: "ECU", name: "Ekvador",             alpha2: "EC" },
  { noc: "ESA", name: "Salvador",            alpha2: "SV" },
  { noc: "GRN", name: "Grenada",             alpha2: "GD" },
  { noc: "GUA", name: "Gvatemala",           alpha2: "GT" },
  { noc: "GUY", name: "Gvajana",             alpha2: "GY" },
  { noc: "HAI", name: "Haiti",               alpha2: "HT" },
  { noc: "HON", name: "Honduras",            alpha2: "HN" },
  { noc: "JAM", name: "Jamajka",             alpha2: "JM" },
  { noc: "LCA", name: "Sveta Lucija",        alpha2: "LC" },
  { noc: "MEX", name: "Meksiko",             alpha2: "MX" },
  { noc: "NCA", name: "Nikaragva",           alpha2: "NI" },
  { noc: "PAN", name: "Panama",              alpha2: "PA" },
  { noc: "PAR", name: "Paragvaj",            alpha2: "PY" },
  { noc: "PER", name: "Peru",                alpha2: "PE" },
  { noc: "PUR", name: "Portoriko",           alpha2: "PR" },
  { noc: "SKN", name: "Sveti Kits i Nevis",  alpha2: "KN" },
  { noc: "SUR", name: "Surinam",             alpha2: "SR" },
  { noc: "TTO", name: "Trinidad i Tobago",   alpha2: "TT" },
  { noc: "URU", name: "Urugvaj",             alpha2: "UY" },
  { noc: "USA", name: "SAD",                 alpha2: "US" },
  { noc: "VEN", name: "Venecuela",           alpha2: "VE" },
  { noc: "VIN", name: "Sveti Vinsent",       alpha2: "VC" },
  // Oceania
  { noc: "ASA", name: "Američka Samoa",      alpha2: "AS" },
  { noc: "AUS", name: "Australija",          alpha2: "AU" },
  { noc: "COK", name: "Kukova Ostrva",       alpha2: "CK" },
  { noc: "FIJ", name: "Fidži",               alpha2: "FJ" },
  { noc: "FSM", name: "Mikronezija",         alpha2: "FM" },
  { noc: "GUM", name: "Guam",                alpha2: "GU" },
  { noc: "KIR", name: "Kiribati",            alpha2: "KI" },
  { noc: "MHL", name: "Maršalska Ostrva",    alpha2: "MH" },
  { noc: "NRU", name: "Nauru",               alpha2: "NR" },
  { noc: "NZL", name: "Novi Zeland",         alpha2: "NZ" },
  { noc: "PLW", name: "Palau",               alpha2: "PW" },
  { noc: "PNG", name: "Papua Nova Gvineja",  alpha2: "PG" },
  { noc: "SAM", name: "Samoa",               alpha2: "WS" },
  { noc: "SOL", name: "Solomonska Ostrva",   alpha2: "SB" },
  { noc: "TGA", name: "Tonga",               alpha2: "TO" },
  { noc: "TUV", name: "Tuvalu",              alpha2: "TV" },
  { noc: "VAN", name: "Vanuatu",             alpha2: "VU" },
  // Neutral / historical
  { noc: "AIN", name: "Neutralni sportisti", alpha2: "AIN" },
  { noc: "SCG", name: "Srbija i Crna Gora",  alpha2: "CS" },
  { noc: "YUG", name: "Jugoslavija",         alpha2: "YU" },
  { noc: "URS", name: "SSSR",                alpha2: "SU" },
] as const;

export type NocEntry = (typeof NOC_LIST)[number];

// ISSF neutral-status codes — RUS/BLR athletes compete as AIN (URS is the
// pre-1992 Soviet code, folded in for old imported results). Display-only:
// underlying nationality stays RUS/BLR/URS in the DB so admin can still tell
// Russian and Belarusian shooters apart.
const NEUTRAL_STATUS_NOCS = new Set(["RUS", "BLR", "URS"]);

export function displayNoc(noc: string | null | undefined): string | null {
  if (!noc) return noc ?? null;
  return NEUTRAL_STATUS_NOCS.has(noc) ? "AIN" : noc;
}
